fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "3.2.0"
    file_concat: https://github.com/electrical/puppet-lib-file_concat.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    "logstash": "#{source_dir}"
