language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
  - 1.8.7
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
  webhooks:
    urls:
      - https://puppet-dev-community.herokuapp.com/event/travis-ci/
    on_success: always
    on_failure: always
    on_start: yes
