language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
  - 1.8.7
env:
  - PUPPET_VERSION=">= 3.0.0"
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
matrix:
  allow_failures:
    - rvm: 2.0.0
  include:
    - rvm: 2.0.0
      env: PUPPET_VERSION=">= 3.0.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION=">= 3.0.0"
notifications:
  email: false
  webhooks:
    urls:
      - https://puppet-dev-community.herokuapp.com/event/travis-ci/
    on_success: always
    on_failure: always
    on_start: yes
